version: "3.9"

volumes:
  db-vol:

services:
  database:
    image: "postgres"
    container_name: "Database"

    volumes:
      - db-vol:/var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "dsrathore"
      POSTGRES_PASSWORD: "admin123"
