name: Farm Product's development branch
run-name: Workflow number ${{github.run_number}} - Dev

on:
  push:
    branches:
      - "dev"

jobs:
  frontend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install NodeJS env
        uses: actions/setup-node@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USR}}
          password: ${{secrets.DOCKER_PWD}}

      - name: Install NodeJS app and Linting test
        run: |
          npm install
          npm run lint

      - name: Build the frontend application of FP
        run: npm run build
